name = "StructuralTransformations"
uuid = "4f93e3cf-3b49-4120-aa20-3ba94fef1cc3"
authors = ["Yingbo Ma <mayingbo5@gmail.com>", "Shashi Gowda <gowda@mit.edu>", "Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "0.1.0"

[deps]
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"

[compat]
ModelingToolkit = "3.6.2"
julia = "1"

[extras]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DiffEqBase", "LinearAlgebra", "OrdinaryDiffEq", "Test", "SafeTestsets"]
